[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Mestrado \- Ciência Florestal<br/>Manejo Florestal de Precisão<br/>\(UFVJM\)
> mmd.emoticon=`tree`


## Prognose

### Modelos de Predição

#### Modelos Baseados em Métricas

##### Validação x IFPC X Fábrica
- NOTE
<pre>A validação entre os modelos de predição e o real (Sendo o real ou IFPC ou a Fábrica - *logmeter- ocorreu para os talhoes onde a medição de campo foi feita com diferença máxima de +/- um mês entre inventário e sobrevoo LiDAR)</pre>

##### Modelagem

###### Modelo Não Linear Tradicional

###### Random Forest Regressor

###### Redes Neurais Artificiais

##### Métricas de ajuste

##### Premissas Básicas
> fillColor=`#00FF00`

- NOTE
<pre>Premissas Básicas do projeto:
	1) Pixel size deve ser similar ao tamanho da parcela de campo;
	2) Sobrevoo LiDAR e Inventário Florestal devem ocorrer concomitantemente para ajuste de modelos;
	3) Desconsiderar talhões com sinistro e nativas;
	4) Desconsiderar talhões com área inferior a 5 ha;
</pre>

#### Modelos Baseados na NP??
> fillColor=`#FF8F00`


### Modelos de Projeção <br/>\(Crescimento e Produção\)

#### Modelos Baseados em Métricas

##### Validação x IFPC X Fábrica

###### Deltas mensais são superiores aos anuais?<br/>Ou não há influencia?
> fillColor=`#FF7200`


##### Cálculos de Delta <br/>\(\*Taxa de Crescimento entre duas métricas raster LiDAR\)

###### Delta/tempo <br/>\(ano | mês\)

####### Métricas de ajuste

####### Modelagem

######## Ajuste MCP \(\*delta\)<br/>Modelo Não Linear Tradicional

######## Ajuste MCP \(\*delta\)<br/>Random Forest Regressor

######## Ajuste MCP \(\*delta\)<br/>Redes Neurais Artificiais

#### Modelos Baseados na NP??
> fillColor=`#FF8F00`


## Otimização de Amostragem
> leftSide=`true`


### Amostragem Casual Simples

### Amostragem Casual Simples em <br/>Intervalo de Confiança

### Amostragem Casual Estratificada

### Amostragem Casual Estratificada em <br/>Intervalo de Confiança

### Amostragem Casual Estratificada em <br/>Intervalo de Confiança para Classes de Idade Principais

## Segmentação de Árvore Individual
> leftSide=`true`


### Segmentação Morfológica

### Segmentação de Mínimos e Máximos Locais

### A densidade de pts/m² <br/>influência na segmentação??
> fillColor=`#FF8100`

