[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Mestrado \- Ciência Florestal<br/>Manejo Florestal de Precisão<br/>\(UFVJM\)
> mmd.emoticon=`tree`


## Forecast

### Modelos de Predição

#### Modelos Baseados em Métricas

##### Premissas Básicas:<br/>1\) Pixel size deve ser similar ao tamanho da parcela de campo;<br/>2\) Sobrevoo LiDAR e Inventário Florestal devem ocorrer concomitantemente para ajuste de modelos;<br/>3\) Desconsiderar talhões com sinistro e nativas;<br/>4\) Desconsiderar talhões com área inferior a 5 ha;<br/>5\) Desconsiderar plantios mais velhoes que 168 meses \(14 anos\);<br/>6\) Desconsiderar plantios mais novos que 36 meses \(3 anos\);<br/>7\) Desconsiderar parcelas com numero de fustes \< 50% do planejado\.
> align=`left`,fillColor=`#009933`


##### Métricas de ajuste

###### Consistência do Banco de Dados

####### Análise de Correlação de Métricas \(Pearson\);<br/>Análise de Recursive Feature Elimination \(RFE\);<br/>Análise de Variance Inflation Factor \(VFI\)\.
> align=`left`


##### Modelagem

###### Modelo Não Linear Tradicional

####### Validação x IFPC X Fábrica
- NOTE
<pre>A validação entre os modelos de predição e o real (Sendo o real ou IFPC ou a Fábrica - *logmeter- ocorreu para os talhoes onde a medição de campo foi feita com diferença máxima de +/- um mês entre inventário e sobrevoo LiDAR)</pre>

###### Random Forest Regressor

###### Redes Neurais Artificiais

#### Modelos Baseados na NP??
> fillColor=`#FF8F00`


### Modelos de Projeção <br/>\(Crescimento e Produção\)

#### Modelos Baseados em Métricas

##### Validação x IFPC X Fábrica

###### Deltas mensais são superiores aos anuais?<br/>Ou não há influencia?
> fillColor=`#FF7200`


##### Cálculos de Delta <br/>\(\*Taxa de Crescimento entre duas métricas raster LiDAR\)

###### Delta/tempo <br/>\(ano | mês\)

####### Métricas de ajuste

####### Modelagem

######## Ajuste MCP \(\*delta\)<br/>Modelo Não Linear Tradicional

######## Ajuste MCP \(\*delta\)<br/>Random Forest Regressor

######## Ajuste MCP \(\*delta\)<br/>Redes Neurais Artificiais

#### Modelos Baseados na NP??
> fillColor=`#FF8F00`


## Otimização de Amostragem
> leftSide=`true`


### Amostragem Casual Simples

### Amostragem Casual Simples em <br/>Intervalo de Confiança

### Amostragem Casual Estratificada

### Amostragem Casual Estratificada em <br/>Intervalo de Confiança

### Amostragem Casual Estratificada em <br/>Intervalo de Confiança para Classes de Idade Principais

## Segmentação de Árvore Individual
> leftSide=`true`


### Segmentação Morfológica

### Segmentação de Mínimos e Máximos Locais

### A densidade de pts/m² <br/>influência na segmentação??
> fillColor=`#FF8100`


## Modelos de Variáveis Dendrométricas \(DAP;HT\)

### Aplicação de Schumacher e Hall \-\> VTCC

#### É uma alternativa melhor??
> fillColor=`#FF7200`

